import React from 'react';
import {Metadata} from "next";

export const metadata: Metadata = {
  title: {
    default: "Auth | Kiwadev",
    template: "%s  | Kiwadev",
    absolute: ""
  },
  description: 'Generated by create next app'
}

const AuthLayout = ({children}) => {
  return (
      <div>
        {children}
      </div>
  );
};

export default AuthLayout;